### ISSUE TITLE
Problems when using python setup.py install

### ISSUE THREAD

**Issue by jnoelke** [IMSY-DKFZ/simpa#110]
The installation process itself works fine. However, while performing simulations, an error occures in the volume creation part:
`raise LookupError(f"No spectrum for the given name exists ({spectrum_name}). Try one of: {self.get_spectra_names()}")
LookupError: No spectrum for the given name exists (Melanin). Try one of: []`

This problem is not present when using `python setup.py develop`

Tested with python 3.8.10 and 3.8.11

**Comment by jgroehl** [comment]
See #102
