### ISSUE TITLE
Z-positioning of MSOTAcuityEcho when using SegmentationBasedVolumeCreationAdapter not intuitive

### ISSUE THREAD

**Issue by mschllnbrg** [IMSY-DKFZ/simpa#118]
When using SegmentationBasedVolumeCreationAdapter the z-positioning of the MSOTAcuityEcho is not intuitive.

It seems that the z-position set in the MSOTAcuityEcho is not the same as the one that is simulated when using the SegmentationBasedVolumeCreationAdapter.

**Comment by kdreher** [comment]
Yes, this was fixed with 09efb30bd5245460a7648026e38b231771a27feb :)
