### ISSUE TITLE
Add CITATION file

### ISSUE THREAD

**Issue by TomTomRixRix** [IMSY-DKFZ/simpa#124]
For users who want to cite SIMPA, it would be nice, if there was a citation option directly available in the GitHub repo. Citations can now be easily added to GitHub repos, here is a [guide](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files). It's probably best to add the SIMPA paper as citation object rather than the repo.

**Comment by jgroehl** [comment]
We could add the following (or a derivate) to the README file:

## Citation

If you use the SIMPA tool, we would appreciate if you cite our Journal publication in the Journal of Biomedical Optics:

Gröhl, Janek, Kris K. Dreher, Melanie Schellenberg, Tom Rix, Niklas Holzwarth, Patricia Vieten, Leonardo Ayala, Sarah E. Bohndiek, Alexander Seitel, and Lena Maier-Hein. *"SIMPA: an open-source toolkit for simulation and image processing for photonics and acoustics."* **Journal of Biomedical Optics** 27, no. 8 (2022): 083010.

```
@article{2022simpatoolkit,
  title={SIMPA: an open-source toolkit for simulation and image processing for photonics and acoustics},
  author={Gr{\"o}hl, Janek and Dreher, Kris K and Schellenberg, Melanie and Rix, Tom and Holzwarth, Niklas and Vieten, Patricia and Ayala, Leonardo and Bohndiek, Sarah E and Seitel, Alexander and Maier-Hein, Lena},
  journal={Journal of Biomedical Optics},
  volume={27},
  number={8},
  pages={083010},
  year={2022},
  publisher={SPIE}
}
```

**Comment by jgroehl** [comment]
Ha I should have clicked on your link, it seems 😄 
Yes, we should definitely do both!
