### ISSUE TITLE
Global and components settings are misleading

### ISSUE THREAD

**Issue by Holzwarth69126** [IMSY-DKFZ/simpa#128]
Example: 
reconstruct_delay_and_sum_pytorch assumes SOS in global settings and sets a default/parameter (1540ms) if not there. However, this convenience function should also check if SOS is set in the component settings and (if not present) set this also as global setting and vice versa. However, when both are set component settings are used (works). Moreover, a warning should raise if global and component setting are not the same. 

Generally missing is a good documentation what should be in global or component settings.

**Comment by jgroehl** [comment]
Agreed the intended behaviour should be well-documented and the implementations of all adapters and convenience functions should be consistent!
> However, when both are set component settings are used (works).

I'm not sure what you mean. Does this work already?

**Comment by Holzwarth69126** [comment]
If I remember correctly, if SOS is set in global and component settings, the component settings SOS is used. @TomTomRixRix and me are going to refactor this together with Issue #127 within the next weeks.
