### ISSUE TITLE
Safety margin in check_prerequisites

### ISSUE THREAD

**Issue by jgroehl** [IMSY-DKFZ/simpa#142]
There is an arbitrary safety margin of 1 mm in most device definitions for checking if a device can be simulated within a certain volume.
For the IPASC/standardised-image-reconstruction project, this is an issue.

I think we should remove this safety margin, or are there potential issues with that?
I think these were introduced to avoid that the detection elements are placed on the outer-most voxel of the volume. In that case, we could re-define the safety margin to be 1 voxel?

**Comment by kdreher** [comment]
Yes, this was done because of detector element positions being placed one voxel outside of the volume.
But I agree that 1 voxel would then make more sense than 1 mm
