### ISSUE TITLE
Users should get a warning/notification if reconstructions runs on CPU.

### ISSUE THREAD

**Issue by Holzwarth69126** [IMSY-DKFZ/simpa#152]
If a user want to reconstruct PA images and cuda is not available (maybe wrong cuda version or no GPU) the code automatically runs on CPU, without notification. We should either warn the user in that case, since it is benefitial to run the reconstruction on GPU. 

See reconstruction_utils.py line 265ff ('# move tensors to GPU if available, otherwise use CPU')

Disclaimer: This could be relevant at different locations!

**Comment by kdreher** [comment]
Fixed by #169
