### ISSUE TITLE
Windows tests seem to succeed despite errors

### ISSUE THREAD

**Issue by TomTomRixRix** [IMSY-DKFZ/simpa#171]
In one of my last commits I had a small error where I forgot to rename a keyword of an argument. This was nicely detected by our automatic tests. Interestingly they only failed on ubuntu and macos but not on windows. 

<img width="540" alt="grafik" src="https://user-images.githubusercontent.com/13121269/185597320-06bc5b76-407b-4105-aa91-a29e3d1c4198.png">

When looking into the corresponding test log, I noticed that the error is thrown but somehow doesn't seem to be passed to the testing environment or is ignored.

```bash
test apodization factors creation
ERROR: test_get_processing_device_with_no_settings (simpa_tests.automatic_tests.test_processing_device.TestProcessing)
tearDown
If cuda is available and no settings are given by the user, verify that a torch GPU device is returned.
setUp
----------------------------------------------------------------------
test envelope detection
Traceback (most recent call last):
tearDown
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\simpa_tests\automatic_tests\test_processing_device.py", line 44, in test_get_processing_device_with_no_settings
setUp
    device = get_processing_device(used_settings=None)
test normalization
TypeError: get_processing_device() got an unexpected keyword argument 'used_settings'
tearDown
```

**Comment by kdreher** [comment]
fixed by #183
