### ISSUE TITLE
Understanding initial pressure values

### ISSUE THREAD

**Issue by MengjieSHI** [IMSY-DKFZ/simpa#189]
Hi, 

I am simulating a string phantom based on _optical_and_acoustic_simulation.py_. it is a linear array based detector and a slit illumination source on top of the simulation area. I got some results like these. 

![initial_pressure_2](https://user-images.githubusercontent.com/59768848/204140966-04cc78b9-1a46-4412-a5e6-ead924cd39db.png)

![initial_pressure_1](https://user-images.githubusercontent.com/59768848/204140954-2d1ece5e-66c3-462e-8d05-30d79a9d3d57.png)

1) why does the first row seem to have lower initial pressure values than those at the deep depth? It doesn't make sense if looking into the reconstruction results. 
2) I added a 0.1 mm horizontal layer at z=1mm.  Why does the layer look like bent towards the end? 
3) What does the colorbar of the reconstruction results represent? Why does it have a different range to the initial pressure values? 

I checked the documentation and paper, but didn't find some relevant discussion (or maybe i missed). any one can help explain a bit? Thank you:)

**Comment by jgroehl** [comment]
Hi Mengjie,

Thanks for your questions!

1. I agree that the first plot does not make sense if the light is coming from straight above the displayed image. Are you sure that the displayed window is taken from the correct slice? Out of plane the image might look very different.
From your reconstruction it looks like you might not be visualising correctly - might be a bug in the visualise script. Can you try manually plotting the initial pressure distribution in your imaging plane?

2. We have a distortion map that can be added to the horizontal layers (e.g. when wanting to simulate curved skin). You have to disable the simulation of distortions in your settings dictionary.

3. The units are the units of the reconstructed signal. While for some reconstruction algorithms the units are the same, this is not necessarily the case (e.g. dmas significantly transforms the output signal)

Hope that at least partially answers your questions :)

**Comment by MengjieSHI** [comment]
> 1. the correct slice

Hi Janek, thanks for your fast response. I check the slice is at the imaging plane, I manually plotted this slice, it is basically the same. The second result with the curve skin seems correct. I didn't change the detection geometry, so they both from the same slice. I am wondering why they look different. 

Thanks for your explanations regarding 2 and 3. They make sense to me now:)

**Comment by jgroehl** [comment]
Could you be so kind as to share the part of your code where you define your settings and the device? Maybe one of us can spot an error!

**Comment by MengjieSHI** [comment]
> Could you be so kind as to share the part of your code where you define your settings and the device? Maybe one of us can spot an error!

Hi Janek, I realised it was because the absorption (scattering) coefficients of the background and strings were set too small. the attenuation was not obvious until the photons arrived at deep depths.  Another thing is about the wavelength. single wavelength (700 nm, Fig1) seemed to generate uneven initial pressure distributions (i.g. the first row) compared to those with dual wavelengths (700&800 nm, Fig2). Do you have any idea about why it happened? Many thanks! 

![image](https://user-images.githubusercontent.com/59768848/204646708-e7363240-9f32-4864-bf68-4b0ceeb44105.png)
![image](https://user-images.githubusercontent.com/59768848/204646748-fcd157d1-f8cb-4552-9b21-a7222f1d52bb.png)

**Comment by MengjieSHI** [comment]
> > Could you be so kind as to share the part of your code where you define your settings and the device? Maybe one of us can spot an error!
> 
> Hi Janek, I realised it was because the absorption (scattering) coefficients of the background and strings were set too small. the attenuation was not obvious until the photons arrived at deep depths. Another thing is about the wavelength. single wavelength (700 nm, Fig1) seemed to generate uneven initial pressure distributions (i.g. the first row) compared to those with dual wavelengths (700&800 nm, Fig2). Do you have any idea about why it happened? Many thanks!
> 
> ![image](https://user-images.githubusercontent.com/59768848/204646708-e7363240-9f32-4864-bf68-4b0ceeb44105.png) ![image](https://user-images.githubusercontent.com/59768848/204646748-fcd157d1-f8cb-4552-9b21-a7222f1d52bb.png)

Hi, I found it was caused by the molecular composition. I assigned _sp.TISSUE_LIBRARY.blood()_ to each string in a loop and the assigned values changed at each iteration (5.68, 3.83, 1.67...) which I didn't expect at all.
