### ISSUE TITLE
Fix `numpy` to <1.24.0

### ISSUE THREAD

**Issue by TomTomRixRix** [IMSY-DKFZ/simpa#191]
Numpy has changed the data type representations slightly, as explained [here](https://github.com/numpy/numpy/pull/22607).
A deprecation now throws an error. Therefore, we might want to set 1.23.2 to be highest numpy version. Or we update our code according to the changes in numy. Perhaps removing `np.bool` and exchanging it with `np.bool_` might be sufficient, I don't know.

**Comment by jgroehl** [comment]
`np.int` and `np.float` definitions are also now raising errors.

Is it even worth it to have these detailed type checks in the first place?
It might be preferable to do the type checking for numbers from the `numbers` package: e.g. `numbers.Integral` or `numbers.Number`?

For booleans, the `np.bool_` options definitely works, but is this the intended usage?
