### ISSUE TITLE
PyPI management with github actions

### ISSUE THREAD

**Issue by jgroehl** [IMSY-DKFZ/simpa#193]
Would it be worth setting up a `release` branch with automatic PyPI upload when being pushed into?

**Comment by TomTomRixRix** [comment]
I'm not sure how complicated the PyPI deployment process is, but if this can easily be automated, then this might be an awesome use case for github actions

**Comment by kdreher** [comment]
I think with the new poetry setup, this should be easily doable.
The command is basically just `poetry publish` with the PyPI credentials as secret

**Comment by TomTomRixRix** [comment]
This issue should be solved with commit [d8b9666](https://github.com/IMSY-DKFZ/simpa/pull/212/commits/d8b96665aebfa334e001f3c615d6c653f5ec6636) by introducing a github action. The action is currently triggered on `push` to the `main` branch which includes merges to the main branch. 

In the future we could discuss how we handle releases. We could use release branches (which is probably the old way of doing it) or GitHub releases. We could also use git tags for that. And write many actions to automate this. But for now this commit is a good start I guess.

**Comment by kdreher** [comment]
solved with #212
