### ISSUE TITLE
Adding diffuse reflectance to SIMPA

### ISSUE THREAD

**Issue by leoyala** [IMSY-DKFZ/simpa#20]
In order to simulate the diffuse reflectance at the surface of the volumes, the top layer has to be all 0's (required by MCX). Therefore, the volume has to be modified in case this requirement is not met. It is not clear how to implement this in the current core of SIMPA. 
One option would be to separate diffuse reflectance simulation from fluence simulations. It has to be taken into account that if it is completely separate, then 2 simulations are required for the same volume when both fluence and diffuse reflectance are desired.

**Comment by jgroehl** [comment]
In the SIMPA meeting on the 26th of March 2021, we decided to separate diffuse reflectance simulations from fluence simulations.
It should hence be integrated as a separate simulation component.
