### ISSUE TITLE
kWaveArray addition now included in kWave 1.4

### ISSUE THREAD

**Issue by faberno** [IMSY-DKFZ/simpa#201]
Since kWaveArray has been added to kWave 1.4, its download link has been removed from the kWave-forum post. So this should probably be changed in the installation guide.

For older versions of kWave the download link of kWaveArray alpha 0.3 was http://www.k-wave.org/downloads/kWaveArray_alpha_0.3.zip

**Comment by kdreher** [comment]
resolved with 2aae9ea8ba126ffff66a40e5081a86abe9ab8d53
