### ISSUE TITLE
Trouble during installation (UnicodeDecodeError)

### ISSUE THREAD

**Issue by cwsbest** [IMSY-DKFZ/simpa#232]
**Describe the bug**
I am trying to install SIMPA in my work PC (Windows 10), and the installation fails with the message saying: 
 "UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 4599: illegal multibyte sequence"
I searched on the Google and probably it could be because I am using Korean in my PC and the encoding is not compatible.
I tried running "chcp 65001" in the command prompt before installation, but it didn't help any. 

Looking at the error messages, I found the error appears when executing something related to 'kwargs'.
I downloaded the SIMPA pip package and found "kwargs" in the setup.py file.
Not sure but maybe there's something in "setup_kwargs" that should be encoded in UTF-8?

 **Specify a priority (low, medium, high)**
Medium

**To Reproduce**
1. Run command prompt and change directory to simpa folder
2. Run "chcp 65001"
3. Run "py -m pip install simpa"

**Current Behavior**

**Expected behavior**

**Screenshots**
![image](https://github.com/IMSY-DKFZ/simpa/assets/141014689/8b73fb14-6a5e-453e-aca8-ec417bb35d54)
![image](https://github.com/IMSY-DKFZ/simpa/assets/141014689/a643fd50-78dc-43f0-8864-9a2647b0e928)

**Environment (please complete the following information):**
 - OS: Windows 10
 - SIMPA version: newest 
 - IDE: Spyder

**Additional context**
Add any other context about the problem here, e.g. possible solution(s).

**Comment by kdreher** [comment]
Thanks for reporting this and for using the new issue template! :) 

In one of your screenshots, it says that you use the simpa version 0.8.11 which is an older version. The current version is 0.8.17.
Also, we have moved from using setup.py as installation configuration file to pyproject.toml.
Maybe you can try it with the newest version?

But I suspect the error will be similar as I think you're right about the encoding being incompatible with Korean symbols.
