### ISSUE TITLE
Error in minimal_optical_simulation.py

### ISSUE THREAD

**Issue by hhapk** [IMSY-DKFZ/simpa#248]
**Describe the bug**
Error is TypeError: _stack_dispatcher() got an unexpected keyword argument 'dtype' when runing minimal_optical_simulation.py.
![image](https://github.com/IMSY-DKFZ/simpa/assets/59441535/559a0c5e-af15-42cb-b042-47d40c21d490).

 **Specify a priority (low, medium, high)**
medium

**To Reproduce**
1. Setup python '3.9', pytorch 1.12.1
2. Setup virtual environment
3. Install SIMPA 'v0.8.20'
4. Run SIMPA script 'Run minimal_optical_simulation.py in Pycharm IDE'
5. See error

**Current Behavior**
minimal_optical_simulation.py break off

**Expected behavior**
finish running minimal_optical_simulation.py

**Screenshots**

**Environment (please complete the following information):**
 - OS: [Ubuntu 18.04.5 LTS]
 - SIMPA version [0.8.20] and git commit hash if possible
 - IDE [Pycharm]

**Additional context**
Add any other context about the problem here, e.g. possible solution(s).

**Comment by kdreher** [comment]
What numpy version do you have?
The `dtype` argument was introduced in numpy version 1.24.0

**Comment by hhapk** [comment]
Thank you! 
The codes could run after installed the numpy==1.24.0. But I have encountered a new problem.
Problem:No such file or directory: './workplace/data/MyVolumeName_471_output.mc2'. Is the mcx can't produce the 'MyVolumeName_471_output.mc2'? or 'MyVolumeName_471_output.mc2' was produced in other path, because i could not make files in the workspace in public servers
![image](https://github.com/IMSY-DKFZ/simpa/assets/59441535/97c60a47-d66d-4e37-8b2c-6fd857b20330)

**Comment by faberno** [comment]
Thats because MCX recently made jnii the default file format. Theres already a [pr](https://github.com/IMSY-DKFZ/simpa/pull/246) to fix this, but it's not merged yet.

**Comment by kdreher** [comment]
This issue should be resolved by now
