### ISSUE TITLE
manual KWaveConvenienceFunction test fails

### ISSUE THREAD

**Issue by TomTomRixRix** [IMSY-DKFZ/simpa#271]
**Describe the bug**
When running the test in `simpa_tests/manual_tests/acoustic_forward_models/KWaveAcousticForwardConvenienceFunction.py` the resulting reconstruction by far doesn't look like the initial pressure. Either the test is poor and doesn't capture the desired behavior or something in the code changes so that the test fails.

 **Specify a priority (low, medium, high)**
medium

**To Reproduce**
1. Setup python
2. Setup virtual environment
3. Install SIMPA and checkout `develop` at the latest commit
4. Run script `simpa_tests/manual_tests/acoustic_forward_models/KWaveAcousticForwardConvenienceFunction.py`
5. See resulting figure

**Current Behavior**
Initial pressure and reconstructed initial pressure don't look similar. Probably the reconstruction is broken.

**Expected behavior**
They should look similar.

**Screenshots**
![TestKWaveConvenienceFunction](https://github.com/IMSY-DKFZ/simpa/assets/13121269/94452a3c-9612-4579-89fa-9a858faaae3d)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - SIMPA a807acece005dbe8ca06390149682c6ede1a3002
 - IDE: VSCode

**Additional context**

**Comment by kdreher** [comment]
Fixed by #271
