### ISSUE TITLE
Add a planar illumination geometry

### ISSUE THREAD

**Issue by RecurvedBow** [IMSY-DKFZ/simpa#279]
**Please describe your :rocket: feature request.**
As a developer who is unfamiliar with the effects of lighting on simulations, I want to define a global light that evenly illuminates the entire tissue to compare different lighting conditions.

**Describe the solution you'd like**
The ideal solution would be to define a planar illumination geometry.

**Describe alternatives you've considered**
An alternative would be to define a PencilArrayIlluminationGeometry with an illuminator defined for each voxel, however, this might not illuminate all spots evenly compared to a planar illumination geometry.

**Comment by faberno** [comment]
I have already worked on this, can open a PR soon.

**Comment by RecurvedBow** [comment]
Sorry, I did not see your comment & have just implemented it, but we can combine our implementations into one single feature.
