### ISSUE TITLE
Floating point rounding error for M1 Mac

### ISSUE THREAD

**Issue by frisograce** [IMSY-DKFZ/simpa#288]
**Describe the bug**
Floating point rounding error when using inequalities in simpa/utils/libraries/structure_library/ParallelepipedStructure.py

 **Specify a priority (low, medium, high)**
High

**To Reproduce**
1. Use M1 mac
2. Setup python , virtual env, simpa
3. Run tests
4. Result: Error in test_parallel_epipeds

**Current Behavior**
Test fails due to rounding point precision errors

**Expected behavior**
Test doesn't fail

**Environment (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - SIMPA version 0.9.1
 - IDE PyCharm

**Comment by jgroehl** [comment]
Wait, the proposed fix actually stops this behaviour? That's interesting, as the two operations looks equivalent :O

**Comment by frisograce** [comment]
Definitely a strange bug, I believe that because it combines the floating points before making the comparisons, it helps to mitigate the rounding errors
