### ISSUE TITLE
Refactor SimulationModule

### ISSUE THREAD

**Issue by TomTomRixRix** [IMSY-DKFZ/simpa#303]
Currently the `SimulationModule` class is defined in the `__init__.py` file under `simpa/core`. However, in a structural perspective it would make sense to separate core methods like `run` from simulation module specific methods such as `get_additional_flags`. 

Suggested solution:
Create a `CoreModule` class in the `core/__init__.py` and move the `SimulationModule` to `core/simulation_modules/__init__.py` and inherit from `CoreModule`.

**Comment by kdreher** [comment]
I'm not sure if I agree with a `CoreModule`. I do see the point of renaming the parent class in the core init, though. I would suggest naming it sth like `PipelineElement`. Then, we could introduce the `SimulationModule` in the SimulationModule package inheriting from the `PipelineElement` as should the `ProcessingComponent`s.  
Also, making everything consistent should be part of this issue, meaning:

- All `SimulationModule` and `ProcessingComponent`s should get their `self.component_settings` and the `self.torch_device` in their `__init__` methods.
- All Base classes in the core should be defined in the `__init__.py` files of their respective packages

**Comment by TomTomRixRix** [comment]
- [ ]  refactor component settings into SimulationModule with abstract method
- [ ] refactor torch device
- [ ] ...
