### ISSUE TITLE
Add possbility to add extra flags for the simulation executables

### ISSUE THREAD

**Issue by jgroehl** [IMSY-DKFZ/simpa#9]

**Comment by jgroehl** [comment]
Tags.MCX_EXTRA_FLAGS might be a good name for this specific field.
I do not think we should implement a general solution that generically works for any executable that is added via a module.

**Comment by jgroehl** [comment]
I have to revise my statement from before, it might be a good idea to add exactly what you asked for 😁 
@leoyala Were you already working on this, or are you happy for me to implement it?

**Comment by leoyala** [comment]
I did not start implementing this yet, so you can start already :)
