### ISSUE TITLE
Device initialisation is unintuitive now

### ISSUE THREAD

**Issue by jgroehl** [IMSY-DKFZ/simpa#98]
Due to the way we represent PA devices and the illumination and detection geometries by the same AbstractDeviceClass, it is currently not clear, how to correctly initialise a PA device. Should both the pa_device and the geometry definitions be getting the position argument, or just one? What happens if only parts of the classes are "correctly" initialised?

-> This might lead to lots of confusion!

**Comment by jgroehl** [comment]
This issue is a leftover from #89

**Comment by kdreher** [comment]
Should be resolved by now
